env:
  global:
    - CC_TEST_REPORTER_ID=c815cc06c282d0eec6709c751088034096c5ff87678018ff4147e4220a0adddd

language: ruby

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
